blank_issues_enabled: false
contact_links:
  - name: Ask Question
    url: https://github.com/21GramConsulting/invertible/discussions
    about: Ask questions and discuss with other community members
